<a href="https://colab.research.google.com/github/hari2001-hash/FreeCodeCamp-Pandas-Real-Life-Example/blob/master/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
n_arra = np.array([[1,2,3],[4,5,6]])

In [5]:
type(n_arra)

numpy.ndarray

In [6]:
n_arra

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np1 = np.array([[4,8,16],[5,15,20]])
np1

array([[ 4,  8, 16],
       [ 5, 15, 20]])

In [10]:
floats = np.array([[2.45,0.000,0.780,44.50],[33.6,87.5,32.4,99]])
floats

array([[ 2.45,  0.  ,  0.78, 44.5 ],
       [33.6 , 87.5 , 32.4 , 99.  ]])

In [11]:
floats.ndim

2

In [12]:
floats.shape

(2, 4)

In [13]:
floats.size

8

In [15]:
intr = np.array([[6,12,18],[8,16,24]])
intr

array([[ 6, 12, 18],
       [ 8, 16, 24]])

In [18]:
intr.shape


(2, 3)

In [19]:
intr.size

6

In [20]:
for rows in intr:
  print(rows)

[ 6 12 18]
[ 8 16 24]


In [22]:
for i in intr.flat:
  print(i)

6
12
18
8
16
24


In [23]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.full((3,7),90)

array([[90, 90, 90, 90, 90, 90, 90],
       [90, 90, 90, 90, 90, 90, 90],
       [90, 90, 90, 90, 90, 90, 90]])

In [34]:
np.arange(30,1,-3)

array([30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [35]:
np.arange(3,70)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [40]:
#to display decimal ordered values in array
np.linspace(2,31)

array([ 2.        ,  2.59183673,  3.18367347,  3.7755102 ,  4.36734694,
        4.95918367,  5.55102041,  6.14285714,  6.73469388,  7.32653061,
        7.91836735,  8.51020408,  9.10204082,  9.69387755, 10.28571429,
       10.87755102, 11.46938776, 12.06122449, 12.65306122, 13.24489796,
       13.83673469, 14.42857143, 15.02040816, 15.6122449 , 16.20408163,
       16.79591837, 17.3877551 , 17.97959184, 18.57142857, 19.16326531,
       19.75510204, 20.34693878, 20.93877551, 21.53061224, 22.12244898,
       22.71428571, 23.30612245, 23.89795918, 24.48979592, 25.08163265,
       25.67346939, 26.26530612, 26.85714286, 27.44897959, 28.04081633,
       28.63265306, 29.2244898 , 29.81632653, 30.40816327, 31.        ])

In [44]:
np.linspace(0,50,num=5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [46]:
np.random.randint(0, 40 ,8)

array([24, 16, 29,  6, 37, 18, 37, 15])

In [52]:
#array sum
Rh = np.random.randint(0,1000,138)
Rh
Rh.sum()

71885

In [56]:
#To finf Maximum, minimum,mean and Standard deviation of an array
Rh.max()
Rh.mean()
Rh.min()
Rh.std()

307.5163454517772

In [57]:
#various operations in np array
h = np.arange(1,20,4)

In [61]:
o = np.random.randint(1,20,5)

In [62]:
o

array([18,  6,  5,  4, 16])

In [63]:
h

array([ 1,  5,  9, 13, 17])

In [64]:
o+h

array([19, 11, 14, 17, 33])

In [65]:
o-h

array([17,  1, -4, -9, -1])

In [66]:
o*h

array([ 18,  30,  45,  52, 272])

In [69]:
o += h*2
o

array([22, 26, 41, 56, 84])

In [70]:
np.sqrt(o)

array([4.69041576, 5.09901951, 6.40312424, 7.48331477, 9.16515139])

In [71]:
o/h

array([22.        ,  5.2       ,  4.55555556,  4.30769231,  4.94117647])

In [72]:
p = np.array([[3,6,45],[9,45,3]])
f = np.array([[78,90,3,5],[52,41,345,89]])


In [74]:
#gives error whwn length of arrays are not equal
#f+p

ValueError: ignored

In [87]:
f+=234

In [88]:
f

array([[468, 468, 468, 468],
       [468, 468, 468, 468]])

In [90]:
np.sqrt(f)

array([[21.63330765, 21.63330765, 21.63330765, 21.63330765],
       [21.63330765, 21.63330765, 21.63330765, 21.63330765]])